name: Numpy User DTypes CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install build and test dependencies
        run: |
          python -m pip install -U pip build pytest unyt wheel meson ninja meson-python patchelf
          pip uninstall -y numpy
          pip install -i https://pypi.anaconda.org/scientific-python-nightly-wheels/simple numpy
          pip install --no-deps -i https://pypi.anaconda.org/scientific-python-nightly-wheels/simple pandas
      - name: Install asciidtype
        working-directory: asciidtype
        run: |
          CFLAGS="-Werror" python -m pip install . --no-build-isolation
      - name: Run asciidtype tests
        working-directory: asciidtype
        run: |
          pytest -vvv --color=yes
      - name: Install metadatadtype
        working-directory: metadatadtype
        run: |
          python -m build --no-isolation --wheel -Cbuilddir=build
          find ./dist/*.whl | xargs python -m pip install
      - name: Run metadatadtype tests
        working-directory: metadatadtype
        run: |
          pytest -vvv --color=yes
      - name: install mpfdtype
        working-directory: mpfdtype
        run: |
          sudo apt install libmpfr-dev -y
          CFLAGS="-Werror" python -m pip install . --no-build-isolation
      - name: Run mpfdtype tests
        working-directory: mpfdtype
        run: |
          pytest -vvv --color=yes
      - name: Install unytdtype
        working-directory: unytdtype
        run: |
          python -m build --no-isolation --wheel -Cbuilddir=build
          find ./dist/*.whl | xargs python -m pip install
      - name: Run unytdtype tests
        working-directory: unytdtype
        run: |
          pytest -vvv --color=yes
      - name: Install quaddtype
        working-directory: quaddtype
        run: |
          python -m build --no-isolation --wheel -Cbuilddir=build
          find ./dist/*.whl | xargs python -m pip install
      - name: Run quaddtype tests
        working-directory: quaddtype
        run: |
          pytest -vvv --color=yes
      - name: Install stringdtype
        working-directory: stringdtype
        run: |
          if [ -d "build/" ]
          then
              rm -r build
          fi
          meson setup build -Db_sanitize=address,undefined
          python -m build --no-isolation --wheel -Cbuilddir=build --config-setting='compile-args=-v' -Csetup-args="-Dbuildtype=debug"
          find ./dist/*.whl | xargs python -m pip install
      - name: Run stringdtype tests
        working-directory: stringdtype
        run: |
          ASAN_OPTIONS=detect_leaks=false LD_PRELOAD=/usr/lib/gcc/x86_64-linux-gnu/11/libasan.so pytest -s -vvv --color=yes
          pip uninstall -y pandas
          ASAN_OPTIONS=detect_leaks=false LD_PRELOAD=/usr/lib/gcc/x86_64-linux-gnu/11/libasan.so pytest -s -vvv --color=yes
