name: Numpy User DTypes CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Update linux dependencies
        run: sudo apt update
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
      - name: Install build and test dependencies
        run: |
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          python -m pip install -U pip build pytest unyt wheel meson ninja meson-python patchelf
          python -m pip install git+https://github.com/numpy/numpy.git
      - name: Install metadatadtype
        working-directory: metadatadtype
        run: |
          python -m build --no-isolation --wheel -Cbuilddir=build
          find ./dist/*.whl | xargs python -m pip install
      - name: Run metadatadtype tests
        working-directory: metadatadtype
        run: |
          pytest -vvv --color=yes
      - name: Install unytdtype
        working-directory: unytdtype
        run: |
          python -m build --no-isolation --wheel -Cbuilddir=build
          find ./dist/*.whl | xargs python -m pip install
      - name: Run unytdtype tests
        working-directory: unytdtype
        run: |
          pytest -vvv --color=yes
